# gcloud builds submit --config=cloudbuild.yaml . --substitutions=TAG_NAME=0.7.2
steps:
- name: maven:3.6.2-jdk-8-slim
  entrypoint: 'mvn'
  args: ['package','-f','./gcp/pubsub/pom.xml']
- name: gcr.io/cloud-builders/docker
  args: ['build', '-t', 'gcr.io/$PROJECT_ID/gcp/pubsub:$TAG_NAME', './gcp/pubsub/']
- name: gcr.io/cloud-builders/docker
  args: ['build', '-t', 'gcr.io/$PROJECT_ID/gcp/pubsub:latest', './gcp/pubsub/']
images: ['gcr.io/$PROJECT_ID/gcp/pubsub']
substitutions:
  TAG_NAME: 0.7.2